language: generic
sudo: false

script:
  - emacs --version
  - make test

env:
  matrix:
    - EVM_EMACS=emacs-24.3-travis
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh || true
  - sed -i 's/"https:/"http:/' ~/.cask/*.el
  - cask upgrade-cask || true
  - evm install $EVM_EMACS --use --skip
  - cask

addons:
  apt:
    packages:
    - gcc
    - g++
    - make
    - automake
    - autoconf
    - libpng-dev
    - libz-dev
    - libpoppler-glib-dev
    - libpoppler-private-dev

notifications:
  email: false
